[project]
name = "tree2md"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Harry Sharma", email = "harshit.2.sharma@kcl.ac.uk" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
tree2md = "tree2md:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
